import { iLoby, iProfile } from '@/types/BasicTypes';
import { debugData } from '@/utils/debugData';

debugData([
  {
    action: 'ui:setupUI',
    data: {
      setLocale: {
        deathmatch_arena: 'ساحة الموت',
        desc_deathmatch_arena:
          'انضم إلى إثارة معارك الموت المكثفة! خطط لإستراتيجيتك، قاتل مع فريقك، وسيطر على الساحة.',
        main_statistics: 'الإحصائيات الرئيسية',
        lobbies: 'الغرف',
        create_lobby: 'إنشاء غرفة',
        kd_rate: 'معدل K/D',
        matches_played: 'عدد المباريات',
        kills_total: 'إجمالي القتلات',
        wins_total: 'إجمالي الانتصارات',
        deaths_total: 'إجمالي الوفيات',
        loses_total: 'إجمالي الخسائر',
        lobby_leader: 'قائد الغرفة',
        start_game: 'بدء اللعبة',
        leave_lobby: 'مغادرة الغرفة',
        red_team: 'الفريق الأحمر',
        blue_team: 'الفريق الأزرق',
        id: 'المعرف',
        kd: 'K/D',
        lobby: 'الغرفة',
        settings: 'الإعدادات',
        current_map: 'الخريطة الحالية',
        lobby_name: 'اسم الغرفة',
        playing_mode: 'وضع اللعب',
        desc_blue_team:
          'الفريق الأزرق يقف متحدًا، مستعدًا للقتال في ساحة الموت. معروف بروح الفريق والتصميم، ويجلب إحساسًا بالوحدة في كل مباراة.',
        desc_red_team:
          'الفريق الأحمر مليء بالحماس والحيوية، دائمًا متعطش للتحدي. بألوانه الجريئة وروحه التنافسية، يضيف الإثارة لكل مواجهة.',
        leader: 'القائد',
        map: 'الخريطة',
        time: 'الوقت',
        player: 'اللاعب',
        management: 'الإدارة',
        join: 'انضمام',
        no_lobby: 'لا توجد غرفة نشطة',
        minutes: 'دقيقة',
        started: 'بدأت',
        new_profile_photo: 'صورة شخصية جديدة',
        save: 'حفظ',
        only_url_error: 'الرابط فقط مسموح!',
        playing_weapon: 'السلاح المستخدم',
      },
      setPlayableWeapons: [
        'weapon_assaultrifle',
        'weapon_pistol',
        'weapon_revolver',
        'weapon_pistol',
        'weapon_revolver',
        'weapon_pistol',
        'weapon_revolver',
        'weapon_pistol',
      ],
    },
  },
  {
    action: 'ui:setUserProfile',
    data: {
      source: 1,
      deaths: 1,
      kd_rate: 1.5,
      kills: 10,
      loses: 1,
      name: 'عبدالله مشالي',
      photo: undefined,
      played_matches: 88,
      wins: 20,
      lobby: {
        id: 1,
        team: 0,
      },
    } as iProfile,
  },
  {
    action: 'ui:setCurrentLobby',
    data: {
      started: true,
      game_time: 10,
      mode: 5,
      finish_time: (new Date().getTime() + 10 * 60 * 1000) / 1000,
      members: [{ kd_rate: 1.2, name: '-a', source: 1, photo: undefined }],
      score: { 0: 1, 1: 12 },
      id: 1,
      leader: { source: 1, name: '-a' },
      map: { image: '', name: 'a' },
      name: "-a's Room",
      weapon: 'weapon_assaultrifle',
    } as iLoby,
  },
] as any);
